version: '3.4'

services:
  db:
    container_name: newbie-backend
    image: mysql:8.0.36
    restart: on-failure
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_HOSTS=admin
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=newbie
      - TZ=Asia/Seoul
    volumes:
      - ./volumes/db:/var/lib/mysql
      - ./volumes/dump:/dump
      - ./my.cnf:/etc/mysql/my.cnf
    command: |
      --sql_mode=NO_ENGINE_SUBSTITUTION --default_storage_engine=InnoDB 
      --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci